---
AUTHOR: "Fabrizio Listello <fabrizio.listello@oracle.com>"
DOMAIN_NAME: myapp-domain-fl
DOMAIN_NAMESPACE: sample-domain1-ns-fl
DOCKER_REPOSITORY: acsitaly01
KUBE_CONFIG: /home/fl118890/Workspace/oci.oraclecloud.com-acs_workshop/.kube/config
WLS_ADMIN_PASSWORD: welcome1
WLS_ADMIN_USER: weblogic

## Application deployment info
APP_NAME: testwebapp
APP_DISTFILE: testwebapp.war
APP_MODULETYPE: war
VER: v1

## Good Defaults
ADMIN_HOST: "{{ DOMAIN_NAME }}-admin-server"
ADMIN_NAME: admin-server
ADMIN_PORT: 7001
CLUSTER_ADMIN: cluster-1,admin-server
CLUSTER_NAME: cluster-1
CONFIGURED_MANAGED_SERVER_COUNT: 2
DEBUG_FLAG: false
DEBUG_PORT: 8453
DOMAIN_SECRET: "{{ DOMAIN_NAME }}-weblogic-credentials"
DOMAIN_UID: "{{ DOMAIN_NAME }}"
JAVA_OPTIONS: "-Dweblogic.StdoutDebugEnabled=false -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv6Addresses=false"

MANAGED_SERVER_NAME_BASE: managed-server-
MANAGED_SERVER_PORT: 8001
PRODUCTION_MODE_ENABLED: true
T3_CHANNEL_PORT: 30012
T3_PUBLIC_ADDRESS: openshift
