#Copyright (c) 2018, 2019 Oracle and/or its affiliates. All rights reserved.
#
#Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#
# ORACLE DOCKERFILES PROJECT
# --------------------------
# This Dockerfile extends the Oracle WebLogic image by creating a sample domain.
#
# ---------------
FROM store/oracle/weblogic:12.2.1.3

MAINTAINER {{ AUTHOR }}

ARG WDT_ARCHIVE
ARG WDT_MODEL

# ---------------------------
ENV ADMIN_NAME={{ ADMIN_NAME }} \
    ADMIN_HOST={{ ADMIN_HOST }} \
    ADMIN_PORT={{ ADMIN_PORT }} \
    MANAGED_SERVER_NAME=${MANAGED_SERVER_NAME} \
    MANAGED_SERVER_PORT={{ MANAGED_SERVER_PORT }} \
    DEBUG_PORT={{ DEBUG_PORT }} \
    ORACLE_HOME=/u01/oracle \
    DOMAIN_NAME={{ DOMAIN_NAME }} \
    DOMAIN_PARENT=${ORACLE_HOME}/user_projects/domains 

ENV DOMAIN_HOME=${DOMAIN_PARENT}/${DOMAIN_NAME} \
    PROPERTIES_FILE_DIR=$ORACLE_HOME/properties \
    SCRIPT_HOME="${ORACLE_HOME}" \
    WDT_HOME="/u01/weblogic-deploy" \
    PATH=$PATH:${ORACLE_HOME}/oracle_common/common/bin:${ORACLE_HOME}/wlserver/common/bin:${DOMAIN_HOME}:${DOMAIN_HOME}/bin:${ORACLE_HOME}

COPY weblogic-deploy.zip /u01
COPY container-scripts/* ${SCRIPT_HOME}/

# Create the properties file directory and the domain home parent with the correct permissions / owner. 
# Unzip and install the WDT image and change the permissions / owner.
USER root
RUN chmod +xw ${SCRIPT_HOME}/*.sh && \
    chown -R oracle:oracle ${SCRIPT_HOME} && \
    mkdir -p $PROPERTIES_FILE_DIR && \
    chown -R oracle:oracle $PROPERTIES_FILE_DIR && \
    chmod -R a+xwr $PROPERTIES_FILE_DIR && \
    mkdir -p $DOMAIN_PARENT && \
    chown -R oracle:oracle $DOMAIN_PARENT && \
    chmod -R a+xwr $DOMAIN_PARENT && \
    cd /u01 && \
    $JAVA_HOME/bin/jar xf weblogic-deploy.zip && \
    rm weblogic-deploy.zip && \
    chmod +xw weblogic-deploy/bin/*.sh && \
    chmod -R +xw weblogic-deploy/lib/python   && \
    chown -R oracle:oracle weblogic-deploy 

# Copy the WDT model, archive file, variable file and credential secrets to the property file directory.
# These files will be removed after the image is built.
# Be sure to build with --force-rm to eliminate this container layer

COPY ${WDT_MODEL} ${WDT_ARCHIVE} ${PROPERTIES_FILE_DIR}/
# --chown for COPY is available in docker version 18 'COPY --chown oracle:oracle'
RUN chown -R oracle:oracle ${PROPERTIES_FILE_DIR}

# Create the domain home in the docker image.
#
# The create domain tool creates a domain at the DOMAIN_HOME location
# The domain name is set using the value in the model / variable files 
# The domain name can be different from the DOMAIN_HOME domain folder name.
#
# Set WORKDIR for @@PWD@@ global token in model file
WORKDIR $ORACLE_HOME
USER oracle
RUN ${WDT_HOME}/bin/createDomain.sh \
        -oracle_home $ORACLE_HOME \
        -java_home $JAVA_HOME \
        -domain_home $DOMAIN_HOME \
        -domain_type WLS \
        -model_file $PROPERTIES_FILE_DIR/${WDT_MODEL##*/} \
        && echo ". $DOMAIN_HOME/bin/setDomainEnv.sh" >> /u01/oracle/.bashrc

# Mount the domain home and the WDT home for easy access.
# VOLUME $DOMAIN_HOME
# VOLUME $WDT_HOME

# Expose admin server, managed server port and domain debug port
EXPOSE $ADMIN_PORT $MANAGED_SERVER_PORT $DEBUG_PORT

WORKDIR $DOMAIN_HOME

# Define default command to start Admin Server in a container.
CMD ["/u01/oracle/startAdminServer.sh"]
