---
- name: Build image
  hosts: build_server
  vars:
    target: "target"
  tasks:
    - debug: var=hostvars verbosity=2
    - file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ target }}"
        - "{{ target }}/container-scripts"
    - copy:
        src: files/weblogic-deploy.zip
        dest: "{{ target }}/weblogic-deploy.zip"
    - copy:
        src: "{{ item }}"
        dest: "{{ target }}/container-scripts"
      with_fileglob:
        - files/container-scripts/*
    - name: Build the model
      template:
        src: wdt-domain-model-base.yaml.j2
        dest: "{{ target }}/wdt-domain-model-base.yaml"
    - name: Build the Dockerfile
      template:
        src: Dockerfile.j2
        dest: "{{ target }}/Dockerfile"
    - name: Build base image
      docker_image:
        path: "./{{ target }}"
        name: "{{ DOCKER_REPOSITORY }}/{{ DOMAIN_NAME }}-base"
        tag: "build"
        dockerfile: Dockerfile
        state: present
        rm: true
        push: false
        buildargs:
          WDT_MODEL: "wdt-domain-model-base.yaml"
          WDT_ARCHIVE: "archive.zip"
      register: image_build
    - debug: var=image_build
    - debug: var=image_build.image.Id
    - docker_image_facts:
        name: "{{ DOCKER_REPOSITORY }}/{{ DOMAIN_NAME }}-base:build"
      register: image_facts
    - debug: var=image_facts.images[0].Id
    - name: Name for set_fact module.
      set_fact:
        DOMAIN_BASE_IMAGE_TAG: "{{ image_facts.images[0].Id | regex_replace('^sha256:','') | truncate(12, True, '') }}"
    - name: Push base image
      docker_image:
        name: "{{ DOCKER_REPOSITORY }}/{{ DOMAIN_NAME }}-base:build"
        repository: "{{ DOCKER_REPOSITORY }}/{{ DOMAIN_NAME }}-base:{{ DOMAIN_BASE_IMAGE_TAG }}"
        push: true
        pull: false
        state: present
    - debug: var=DOMAIN_BASE_IMAGE_TAG

- name: Build Image with applications
  hosts: build_server
  vars:
    target: "target_app"
  tasks:
    - file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ target }}"
        - "{{ target }}/wlsdeploy"
        - "{{ target }}/wlsdeploy/applications"
    - name: Prepare application archive
      copy:
        src: "applications/{{ APP_DISTFILE }}"
        dest: "{{ target }}/wlsdeploy/applications"
    - name: Create archive module.
      archive:
        dest: "{{ target }}/archive.zip"
        format: "zip"
        path: "{{ target }}/wlsdeploy"
    - name: Build the model
      template:
        src: wdt-domain-model-app.yaml.j2
        dest: "{{ target }}/wdt-domain-model-app.yaml"
    - name: Build the Dockerfile
      template:
        src: Dockerfile_app.j2
        dest: "{{ target }}/Dockerfile"
    - name: Build image with app
      docker_image:
        path: "./{{ target }}"
        name: "{{ DOCKER_REPOSITORY }}/{{ DOMAIN_NAME }}-{{ VER }}"
        tag: "build"
        dockerfile: Dockerfile
        state: present
        rm: true
        buildargs:
          WDT_MODEL: "wdt-domain-model-app.yaml"
          WDT_ARCHIVE: "archive.zip"
      register: image_build
