---
- name: Build image
  hosts: build_server
  vars:
    target_base: "target"
  tasks:
    - debug: var=hostvars verbosity=2
    - file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ target_base }}"
        - "{{ target_base }}/container-scripts"
    - name: Add WDT to image
      copy:
        src: files/weblogic-deploy.zip
        dest: "{{ target_base }}/weblogic-deploy.zip"
    - name: Add misc scripts to image
      copy:
        src: "{{ item }}"
        dest: "{{ target_base }}/container-scripts"
      with_fileglob:
        - files/container-scripts/*
    - name: Prepare domain base archive
      archive:
        dest: "{{ target_base }}/archive.zip"
        format: "zip"
        path: "domain/"
    - name: Build the model
      template:
        src: wdt-domain-model-base.yaml.j2
        dest: "{{ target_base }}/wdt-domain-model-base.yaml"
    - name: Build the Dockerfile
      template:
        src: Dockerfile.j2
        dest: "{{ target_base }}/Dockerfile"
    - name: Build base image
      docker_image:
        path: "./{{ target_base }}"
        name: "{{ DOCKER_REPOSITORY }}/{{ DOMAIN_NAME }}-base"
        tag: "build"
        dockerfile: Dockerfile
        state: present
        rm: true
        push: false
        buildargs:
          WDT_MODEL: "wdt-domain-model-base.yaml"
          WDT_ARCHIVE: "archive.zip"
      register: image_build
    - docker_image_facts:
        name: "{{ DOCKER_REPOSITORY }}/{{ DOMAIN_NAME }}-base:build"
      register: image_facts
    - name: Name for set_fact module.
      set_fact:
        DOMAIN_BASE_IMAGE_TAG: "{{ image_facts.images[0].Id | regex_replace('^sha256:','') | truncate(12, True, '') }}"
    - name: Push base image
      docker_image:
        name: "{{ DOCKER_REPOSITORY }}/{{ DOMAIN_NAME }}-base:build"
        repository: "{{ DOCKER_REPOSITORY }}/{{ DOMAIN_NAME }}-base:{{ DOMAIN_BASE_IMAGE_TAG }}"
        push: true
        pull: false
        state: present
    - name: Save DOMAIN_BASE_IMAGE_TAG to file
      copy:
        dest: "{{ target_base }}/domain_base_image_tag.yaml"
        content: |
          DOMAIN_BASE_IMAGE_TAG: {{ DOMAIN_BASE_IMAGE_TAG }}
    - debug: var=DOMAIN_BASE_IMAGE_TAG

# - name: Build Image with applications
#   hosts: build_server
#   vars:
#     target: "target_app"
#   tasks:
#     - file:
#         path: "{{ item }}"
#         state: directory
#       with_items:
#         - "{{ target_base }}"
#         - "{{ target_base }}/wlsdeploy"
#         - "{{ target_base }}/wlsdeploy/applications"
#     - name: Prepare application archive
#       copy:
#         src: "applications/{{ APP_DISTFILE }}"
#         dest: "{{ target_base }}/wlsdeploy/applications"
#     - name: Create archive module.
#       archive:
#         dest: "{{ target_base }}/archive.zip"
#         format: "zip"
#         path: "{{ target_base }}/wlsdeploy"
#     - name: Build the model
#       template:
#         src: wdt-domain-model-app.yaml.j2
#         dest: "{{ target_base }}/wdt-domain-model-app.yaml"
#     - name: Build the Dockerfile
#       template:
#         src: Dockerfile_app.j2
#         dest: "{{ target_base }}/Dockerfile"
#     - name: Build image with app
#       docker_image:
#         path: "./{{ target_base }}"
#         name: "{{ DOCKER_REPOSITORY }}/{{ DOMAIN_NAME }}-{{ VER }}"
#         tag: "build"
#         dockerfile: Dockerfile
#         state: present
#         rm: true
#         buildargs:
#           WDT_MODEL: "wdt-domain-model-app.yaml"
#           WDT_ARCHIVE: "archive.zip"
#       register: image_build
